### ISSUE TITLE
Obtain user data: followers_count, statuses_count, name, screen_name, description

### ISSUE THREAD

**Issue by aberbenni** [JohnnyTheTank/apiNG-plugin-codebird#15]
Is it possible to obtain users/lookup.json?user_id=xxxxxxxxxx info?

**Comment by JohnnyTheTank** [comment]
@aberbenni is this not enough? https://github.com/JohnnyTheTank/apiNG-plugin-codebird#requests-by-user

**Comment by JohnnyTheTank** [comment]
@aberbenni if you want, I could give you live support via gitter: https://gitter.im/JohnnyTheTank/apiNG

we can discuss there what you need

**Comment by JohnnyTheTank** [comment]
close for now
